# Generated by Django 3.2.5 on 2021-07-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210712_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='wsp',
            field=models.IntegerField(default=0),
        ),
    ]
