# Generated by Django 3.2.6 on 2021-09-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='cv',
            field=models.FileField(null=True, upload_to='presentations/cvs'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='presentation/images'),
        ),
    ]
