# Generated by Django 3.2.6 on 2021-09-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_auto_20210918_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='cv',
            field=models.FileField(null=True, upload_to='presentation/cvs'),
        ),
    ]
