# Generated by Django 3.2.5 on 2021-07-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='CategoriesModel',
        ),
    ]
